{"name": "test_login_fail_invalid_data_pwd[case0]", "status": "passed", "parameters": [{"name": "case", "value": "{'user': '15618275180', 'passwd': '', 'check': '密码不能为空'}"}], "start": 1646644856476, "stop": 1646644861250, "uuid": "462e8bf1-fb11-47e1-856d-79d65896dcbb", "historyId": "9538ef1a7d4970037e1b3eead011e344", "testCaseId": "170ec3487b3ed82b8e7aba4de98c62a4", "fullName": "TestCases.test_login.TestLogin#test_login_fail_invalid_data_pwd", "labels": [{"name": "feature", "value": "企业版登录页面-测试用户登录功能"}, {"name": "story", "value": "登录功能-密码下方错误提示用例"}, {"name": "tag", "value": "@pytest.mark.usefixtures('testlogin_back')"}, {"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "2144-20210708JN"}, {"name": "thread", "value": "209740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}