{"name": "test_login_fail_invalid_data_user[case1]", "status": "passed", "parameters": [{"name": "case", "value": "{'user': '15618275180', 'passwd': '12345678', 'check': '用户名不存在或密码不正确'}"}], "start": 1646644840363, "stop": 1646644845147, "uuid": "9c67a8aa-b387-47af-ad72-7ee5c84ad8f6", "historyId": "02f38ff918e61afae4a3b8441ba6a677", "testCaseId": "10c4d51ec017e7c5efc5b856eeff46b2", "fullName": "TestCases.test_login.TestLogin#test_login_fail_invalid_data_user", "labels": [{"name": "feature", "value": "企业版登录页面-测试用户登录功能"}, {"name": "story", "value": "登录功能-用户名下方错误提示用例"}, {"name": "tag", "value": "@pytest.mark.usefixtures('testlogin_back')"}, {"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "2144-20210708JN"}, {"name": "thread", "value": "209740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}